Extract validation from controller
LucasLeandro1204/simple-tasklist pull request #3
Opened 2019-04-16 13:30 UTC by nickdavies791

Extracts validation into form request classes `StoreTask `and `UpdateTask `and passes the `$request` data to the job dispatcher. Tidies up comments.

2019-04-16 13:47 UTC, LucasLeandro1204 requested changes
Hey, thank you for your contribution =)

Requested some changes, mostly (if not they all) are related to annotations vs typehint

2019-04-16 13:47 UTC, LucasLeandro1204 commented on phpunit.xml
> +        <env name="DB_DATABASE" value="database.testing.sqlite"/>
Please rollback this
sqlite running in memory is faster

2019-04-16 13:47 UTC, LucasLeandro1204 commented on app/Jobs/UpdateTask.php
> +     * @param array $attributes
you can drop this annotations since we are type hinting the properties

2019-04-16 13:47 UTC, LucasLeandro1204 commented on app/Jobs/DeleteTask.php
> +     * @param Task $task
same

2019-04-16 13:47 UTC, LucasLeandro1204 commented on app/Jobs/CreateTask.php
> +     * @param bool $status
same

2019-04-16 13:47 UTC, LucasLeandro1204 commented on app/Http/Requests/UpdateTask.php
> +    public function rules()
Use type hint instead of annotation

```suggestion
    public function rules(): array
```

2019-04-16 13:47 UTC, LucasLeandro1204 commented on app/Http/Requests/UpdateTask.php
> +    public function authorize()
same

2019-04-16 13:47 UTC, LucasLeandro1204 commented on app/Http/Requests/StoreTask.php
> +    public function rules()
same

2019-04-16 13:47 UTC, LucasLeandro1204 commented on app/Http/Requests/StoreTask.php
> +    public function authorize()
same

2019-04-16 13:47 UTC, LucasLeandro1204 commented on app/Http/Controllers/TaskController.php
> +     * @param Task $task
you can drop these annotations too

2019-04-16 13:47 UTC, LucasLeandro1204 commented on app/Http/Controllers/TaskController.php
> +use App\Http\Requests\StoreTask;
Please, order imports by length > alphabetically

2019-04-17 09:30 UTC, nickdavies791 commented
Thanks. Saw the project and thought I'd try forking and updating for the first time!

I've made the requested changes and pushed in another commit.

2019-04-17 14:04 UTC, LucasLeandro1204 approved these changes

2019-04-17 14:05 UTC, LucasLeandro1204 commented
Haha thank you bro, great contribution =)

2019-04-17 14:05 UTC, merged